version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: boardTest
      MYSQL_DATABASE: boardTest
      MYSQL_USER: adminBoardTest
      MYSQL_PASSWORD: BoardTest1234
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: adminBoardTest
      PMA_PASSWORD: BoardTest1234
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
